dekanat_4/dekanat_4/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('mainapp.urls', namespace='main')),
    path('admin/', admin.site.urls),
]

dekanat_4/mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),

]

dekanat_4/mainapp/models.py
from django.db import models


class Group(models.Model):
    name = models.CharField(verbose_name='Название группы', max_length=256)
    desc = models.TextField(verbose_name='Специальность')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'группа'
        verbose_name_plural = 'группы'


class Student(models.Model):
    surname = models.CharField(verbose_name='Фамилия', max_length=128)
    name = models.CharField(verbose_name='Имя', max_length=128)
    patronymic = models.CharField(verbose_name='Отчество', max_length=128, blank=True)
    group = models.ForeignKey(Group, verbose_name='Группа', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} | {self.surname} | {self.group}'

    class Meta:
        verbose_name = 'студент'
        verbose_name_plural = 'студенты'

dekanat_4/mainapp/views.py
from django.shortcuts import render

def index(request):
    context = {
        'title': 'Home',
    }
    return render(request, 'mainapp/index.html', context)

dekanat_4/mainapp/templates/mainapp/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{{ title|capfirst }} | decanat</title>
</head>
<body>
<header>
    <ul>
        <li><a href="{% url 'mainapp:index' %}">Главная</a></li>

            <li><a href="#">Создать группу</a></li>

    </ul>
</header>
<div>
    {% block content %}

    {% endblock %}
</div>


</body>
</html>

dekanat_4/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}


{% block content %}

{% endblock %}